#########################################################################
# Title:         Cloudbox: Sanity Check | Tags Check                    #
# Author(s):     desimaniac, EnorMOZ                                    #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Tags Check | Ensure TAGS are not being skipped
  assert:
    that:
      - '"{{ item }}" not in ansible_skip_tags'
    msg: "The tag you are trying to run is currently being skipped. Check your 'ansible.cfg' file."
    quiet: yes
  loop: "{{ ansible_run_tags }}"
  when:
   - not continuous_integration
   - "'cloudbox_' not in playbook_dir"
   - "'community' not in playbook_dir"

# http://blog.leifmadsen.com/blog/2017/01/04/finding-available-ansible-tags-in-playbooks-and-roles/

- name: Tags Check | Get all available TAGS
  shell: |
    ansible-playbook cloudbox.yml --list-tags 2>&1 | grep "TASK TAGS" \
      | cut -d":" -f2 | awk '{sub(/\[/, "")sub(/\]/, "")}1' | sed -e 's/,//g' | xargs -n 1 | sort -u
  register: available_tags
  changed_when: no
  check_mode: no
  when:
   - not continuous_integration
   - "'cloudbox_mod' not in playbook_dir"
   - "'community' not in playbook_dir"

- name: Tags Check | Ensure TAGS are valid
  assert:
    that:
      - '"{{ item }}" in available_tags.stdout_lines'
    msg: >-
      You must supply valid tag(s) via '--tags TAG'
      (get a list of valid tags by running 'ansible-playbook cloudbox.yml --list-tags')
    quiet: yes
  loop: "{{ ansible_run_tags }}"
  when:
   - not continuous_integration
   - "'cloudbox_' not in playbook_dir"
   - "'community' not in playbook_dir"
