#########################################################################
# Title:         Cloudbox: Nvidia | nvtop Tasks                         #
# Author(s):     desimaniac, l3uddz                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: nvtop | Install nvtop dependencies
  apt:
    state: present
    update_cache: yes
    name:
      - cmake
      - libncurses5-dev
      - libncursesw5-dev

- name: nvtop | Pull nvtop repo from github
  git: clone=yes repo="{{ nvidia_nvtop_git_repo_url }}" dest=/tmp/nvtop/
  register: nvtop_repo_clone_status

- name: nvtop | Tasks when nvtop repo is cloned
  block:

  - name: nvtop | Build and install nvtop
    shell: "{{ nvidia_nvtop_binary_build_command }}"

  - name: nvtop | Get nvtop binary version
    shell: "{{ nvidia_nvtop_binary_version_lookup_command }}"
    register: nvtop_binary_version
    ignore_errors: yes

  - name: nvtop | Display nvtop binary version
    debug:
      msg: "nvtop {{ nvtop_binary_version.stdout }} installed."

  when: nvtop_repo_clone_status is succeeded
