#########################################################################
# Title:         Cloudbox: Docker | Network Tasks                       #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Network | Lookup '{{ docker_networks_common_name }}' Docker network
  docker_network_info:
    name: "{{ docker_networks_common_name }}"
  register: _docker_networks_common_name_lookup

- name: Network | Create '{{ docker_networks_common_name }}' Docker network
  docker_network:
    name: "{{ docker_networks_common_name }}"
    state: present
  when: not _docker_networks_common_name_lookup.exists
