#########################################################################
# Title:         Cloudbox: Nethogs Role                                 #
# Author(s):     EnorMOZ, desimaniac                                    #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Make sure NetHogs package is not installed
  apt: "name=nethogs state=absent"

- name: Install NetHogs dependencies
  apt:
    name:
      - build-essential
      - libncurses5-dev
      - libpcap-dev
    state: present
    update_cache: yes

- name: Pull NetHogs repo from github
  git:
    repo: "{{ nethogs_git_repo_url }}"
    dest: "{{ nethogs_git_repo_dest }}"
    clone: yes
    version: HEAD
    force: yes
  register: nethogs_clone_status

- name: Tasks to do with git clone is a success
  block:

  - name: Build and install NetHogs
    shell: "{{ nethogs_binary_build_command }}"

  - name: Get NetHogs binary version
    shell: "{{ nethogs_binary_version_lookup_command }}"
    register: nethogs_binary_version

  - name: Display nethogs binary version
    debug:
      msg: "NetHogs {{ nethogs_binary_version.stdout }} installed."

  when: nethogs_clone_status is succeeded
