#########################################################################
# Title:         Cloudbox: NZBThrottle  | Default Variables             #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

nzbthrottle_name: nzbthrottle

################################
# Paths
################################

nzbthrottle_paths_folder: "{{ nzbthrottle_name }}"
nzbthrottle_paths_location: "{{ server_appdata_path }}/{{ nzbthrottle_paths_folder }}"
nzbthrottle_paths_folders_list:
  - "{{ nzbthrottle_paths_location }}"
nzbthrottle_paths_config_location: "{{ nzbthrottle_paths_location }}/config.json"

################################
# Docker
################################

# Container
nzbthrottle_docker_container: "{{ nzbthrottle_name }}"

# Image
nzbthrottle_docker_image_tag: "latest"
nzbthrottle_docker_image: "daghaian/nzbthrottle:{{ nzbthrottle_docker_image_tag }}"

# Envs
nzbthrottle_docker_envs_default:
  TZ: "{{ tz }}"
nzbthrottle_docker_envs_custom: {}
nzbthrottle_docker_envs: "{{ nzbthrottle_docker_envs_default
                                  | combine(nzbthrottle_docker_envs_custom) }}"

# Volumes
nzbthrottle_docker_volumes_default:
  - "{{ nzbthrottle_paths_config_location }}:/nzbthrottle/config.json:ro"
  - "/mnt:/mnt"
nzbthrottle_docker_volumes_custom: []
nzbthrottle_docker_volumes: "{{ nzbthrottle_docker_volumes_default
                                    + nzbthrottle_docker_volumes_custom }}"

# Labels
nzbthrottle_docker_labels_default: {}
nzbthrottle_docker_labels_custom: {}
nzbthrottle_docker_labels: "{{ docker_labels_common
                                    | combine(nzbthrottle_docker_labels_default)
                                    | combine(nzbthrottle_docker_labels_custom) }}"

# Hostname
nzbthrottle_docker_hostname: "{{ nzbthrottle_name }}"

# Networks
nzbthrottle_docker_networks_alias: "{{ nzbthrottle_name }}"
nzbthrottle_docker_networks_default: []
nzbthrottle_docker_networks_custom: []
nzbthrottle_docker_networks: "{{ docker_networks_common
                                      + nzbthrottle_docker_networks_default
                                      + nzbthrottle_docker_networks_custom }}"
