#########################################################################
# Title:         Cloudbox: Hostess Role                                 #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Get latest Hostess download URL
  shell: "{{ hostess_download_url_lookup_command }}"
  args:
    executable: /bin/bash
  register: hostess_download_url
  ignore_errors: yes

- name: Install Hostess
  get_url:
    url:  "{{ hostess_download_url.stdout | default(hostess_download_url_backup,true) }}"
    dest: "{{ hostess_binary_path }}"
    mode: 0775
    owner: root
    group: root
    force: yes
    validate_certs: no
  ignore_errors: yes
  register: hostess_download_status

- name: Tasks to do when Hostess download is successful
  block:

  - name: Get Hostess binary version
    shell: "{{ hostess_binary_version_lookup_command }}"
    register: hostess_binary_version
    ignore_errors: yes

  - name: Display Hostess binary version
    debug:
      msg: "Hostess {{ hostess_binary_version.stdout }} installed."

  when: hostess_download_status is succeeded
