#########################################################################
# Title:         Cloudbox: Node.js | Frontail                           #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Frontail | Install NPM module
  npm: "name={{ item }} global=yes state=present"
  with_items:
    - frontail

- name: Frontail | Get binary version
  shell: "{{ nodejs_frontail_binary_version_lookup_command }}"
  register: frontail_binary_version

- name: Frontail | Display binary version
  debug:
    msg: "Frontail {{ frontail_binary_version.stdout }} installed."
  when: frontail_binary_version.stdout | trim | length > 0
