#########################################################################
# Title:         Cloudbox: Node.js | Hastebin                           #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Hastebin | Install NPM module
  npm: "name={{ item }} global=yes state=present"
  with_items:
    - hastebin

- name: Hastebin | Lookup binary path
  stat:
    path: "{{ nodejs_hastebin_binary_path }}"
  register: hastebin_binary

- name: Hastebin | Display install confirmation
  debug:
    msg: "Hastebin installed."
  when: hastebin_binary.stat.exists
